### ISSUE TITLE
Why do we need rvm-patchsets?

### ISSUE THREAD

**Issue by josisusan** [cloudfactory/ruby#6]
@kajisaap dai
As I was looking over the Dockerfile, I found that we have used rvm-patchsets on ruby 2.4.x. It is commented on 2.4.x but used on ruby below 2.3.x. 
Why do we need those patches?

I would also like to build Dockerfile for ruby 2.5.x. Do we need to include those lines on new files?

**Comment by kajisaap** [comment]
@josisusan thanks for pointing that out. I can see your PR https://github.com/cloudfactory/ruby/pull/7 - thanks for that too. 

>Why do we need those patches?

RVM-patchsets are some community provided ruby VM enhancements as mentioned in the [README](https://github.com/cloudfactory/ruby/blob/master/README.md). As they are not a standard part of the official ruby distribution, it comes with a "warning ⚠️ " sign but be assured of its' quality as these are mostly contributed by well-known ruby hackers. 

>As I was looking over the Dockerfile, I found that we have used rvm-patchsets on ruby 2.4.x. It is commented on 2.4.x but used on ruby below 2.3.x.

It is not necessary but we may want to include for the sake of consistency in old releases. Again, these patches are contributed and tested by ruby hacker community so there is usually a delay in release. 
Patches for ruby 2.5 just got added here - https://github.com/skaes/rvm-patchsets/tree/master/patches/ruby/2.5/head/railsexpress 

If you could include that in PR, it would be awesome but if not, no worries.
