### ISSUE TITLE
Erroneous env DEBIAN_FRONTEND

### ISSUE THREAD

**Issue by sameergautam** [cloudfactory/ruby#8]
Our Dockerfile has the environment variable DEBIAN_FRONTEND set to `noninteractive`. However, according to [documentation/faq](https://docs.docker.com/engine/faq/#why-is-debian_frontendnoninteractive-discouraged-in-dockerfiles), this is not a good practice. Further details below.

Copying as is from Docker faq:

> Why is DEBIAN_FRONTEND=noninteractive discouraged in Dockerfiles?
> When building Docker images on Debian and Ubuntu you may have seen errors like:
> unable to initialize frontend: Dialog
> These errors don’t stop the image from being built but inform you that the installation process tried to open a dialog box, but was unable to. Generally, these errors are safe to ignore.
> 
> Some people circumvent these errors by changing the DEBIAN_FRONTEND environment variable inside the Dockerfile using:
> 
> ENV DEBIAN_FRONTEND=noninteractive
> This prevents the installer from opening dialog boxes during installation which stops the errors.
> 
> While this may sound like a good idea, it may have side effects. The DEBIAN_FRONTEND environment variable will be inherited by all images and containers built from your image, effectively changing their behavior. People using those images will run into problems when installing software interactively, because installers will not show any dialog boxes.
> 
> Because of this, and because setting DEBIAN_FRONTEND to noninteractive is mainly a ‘cosmetic’ change, we discourage changing it.
> 
> If you really need to change its setting, make sure to change it back to its default value afterwards.

**Comment by kajisaap** [comment]
@sameergautam thanks for digging this. Did we randomly find this or we actually stumbled to a problem because of this?

Please open up a PR to remove this and we will merge it to the master.

**Comment by kajisaap** [comment]
Addressed by https://github.com/cloudfactory/ruby/pull/11
